name: test-wasta-offline-setup # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Set up a Wasta-Offline 'local cache repository' # 79 char long summary
description: |
  Set up a Wasta-Offline 'local cache repository'

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

apps:
  test-wasta-offline-setup:
    command: desktop-launch $SNAP/usr/bin/wasta-offline-setup
    plugs:
      - home
      - removable-media

parts:
  add-ppa:
    plugin: nil
    override-build: |
      apt-get update
      apt-get install software-properties-common --yes
      add-apt-repository --yes ppa:wasta-linux/wasta-apps
      apt-get update
      apt-get upgrade
      
  wasta-offline-setup:
    plugin: nil
#    organize:
#      usr/bin/wasta-offline-setup: bin/wasta-offline-setup
    after: [add-ppa, desktop-gtk3]
    stage-packages:
      - wasta-offline-setup

  dpkg-dev:
    plugin: nil
#    organize:
#      usr/bin/dpkg-scanpackages: bin/dpkg-scanpackages
    stage-packages:
      - dpkg-dev
  
  rename:
    plugin: nil
#    organize:
#      usr/bin/rename: bin/rename
    stage-packages:
      - rename
  
  rsync:
    plugin: nil
#    organize:
#      usr/bin/rsync: bin/rsync
    stage-packages:
      - rsync
    
  zenity:
    plugin: nil
    organize:
      usr/share/zenity: usr/share/zenity
    stage-packages:
      - zenity
