name: test-wasta-offline-setup # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Set up a Wasta-Offline 'local cache repository' # 79 char long summary
description: |
  Set up a Wasta-Offline 'local cache repository'

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

# TODO:
#   - rename command not found in spite of installed package
#   - can't look at log (presented with font selection instead)

apps:
  test-wasta-offline-setup:
    command: desktop-launch $SNAP/bin/wasta-offline-setup
    environment:
#      PERL5LIB: "$SNAP/usr/lib/x86_64-linux-gnu/perl-base/:$SNAP/usr/lib/x86_64-linux-gnu/perl5/5.22/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.22.1/:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.22/:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.22.1/"
      PERL5LIB: "$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.22.1/:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.22/:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.22.1/:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.22/"
    plugs:
      - desktop
      - home
      - removable-media

parts:
  add-pkgs:
    plugin: nil
    organize:
      usr/bin/file-rename: bin/rename
    stage-packages:
      - libdb5.3                # otherwise pulled from host
      - lsb-release
      - rename
      - rsync
      - dpkg-dev
      - libgdk-pixbuf2.0-0      # yad
      - libgtk-3-0              # yad
      - libnotify4              # yad
      - yad      

  # Substituting yad for zenity, courtesy of @galgalesh.
  # https://forum.snapcraft.io/t/winesnap-creating-snaps-for-windows-applications/6392
  wasta-offline-setup:
    after: [desktop-gtk3, add-pkgs]
    plugin: dump
    source: snap/scripts
    organize:
      zenity: bin/zenity
      wasta-offline-setup: bin/wasta-offline-setup
    prime:
      - bin/zenity
      - bin/wasta-offline-setup
    build-attributes:
      - no-system-libraries
