name: test-wasta-offline-setup # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Set up a Wasta-Offline 'local cache repository' # 79 char long summary
description: |
  Set up a Wasta-Offline 'local cache repository'

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

apps:
  wasta-offline-setup:
    command: wasta-offline-setup
    plugs:
      - home
      - removable-media

parts:
  add-ppa:
    plugin: nil
#    after: [desktop-qt4]
    override-build: |
      apt-get update
      apt-get install software-properties-common --yes
      add-apt-repository --yes ppa:wasta-linux/wasta-apps
      apt-get update
      apt-get upgrade
      
  wasta-offline-setup:
    plugin: nil
    organize:
      wasta-offline-setup: /usr/bin/wasta-offline-setup
    after: [add-ppa]
    stage-packages:
      - wasta-offline-setup

  dpkg-dev:
    plugin: nil
    organize:
      usr/bin/dpkg-scanpackages: /usr/bin/dpkg-scanpackages
    stage-packages:
      - dpkg-dev
  
  rename:
    plugin: nil
    organize:
      usr/bin/rename: /usr/bin/rename
    stage-packages:
      - rename
  
  rsync:
    plugin: nil
    organize:
      usr/bin/rsync: /usr/bin/rsync
    stage-packages:
      - rsync
    
  zenity:
    plugin: nil
    organize:
      usr/bin/zenity: /usr/bin/zenity
    stage-packages:
      - zenity
